[executor_evm]
executor_port = 50002
eth_compatibility = false
db_path = 'data'
domain = "test-chain-node1"

[executor_evm.log_config]
max_level = "info"
filter = "info"
# rolling_file_path = "./logs"
service_name = "consensus"
# agent_endpoint = "127.0.0.1:6831"
