# Copyright Rivtower Technologies LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "executor"
version = "6.3.1-alpha.1"
authors = ["Yieazy <yuitta@163.com>", "Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.14"
log4rs = { version = "1.0", features = ["gzip"] }
dotenv = "0.15.0"
cita-logger = "0.1.1"
tonic = "0.5"
git-version = "0.3"
prost = "0.8"
cita-database = "0.1"
tokio = { version = "1.3", features = ["full"] }
clap = { version = "3.0.14", features = ["derive"] }
crossbeam-channel = "0.5.1"
hex = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bloomchain = "0.2"
lazy_static = "1.4.0"
time = "0.3"
rustc-hex = "2.0"
cita_trie = "2.0.0"
byteorder = { version = "1", default-features = false }
bincode = "1.3.3"
rustc-serialize = "0.3"
lru-cache = "0.1.1"
rand = "0.8"
transient-hashmap = "0.4.0"
ethabi = "14.1.0"
largest-remainder-method = "0.1"
parking_lot = "0.11"
ethbloom = "0.11"
sha3 = { version="0.9", optional=true }
tiny-keccak = { version="2.0.0", optional=true }
hashbrown = { version = "0.11", features = ["rayon"] }
hasher = { version="0.1" }
ethereum-types = "0.12"
backtrace = "0.3"

cita-merklehash = "0.1"
cita-secp256k1 = "0.1"
cita-crypto = "0.1"
rlp = "0.5"
util = { package = "cita-util", version = "0.1" }
hashable = { package = "cita-hashable", version = "0.1" }
libproto = { git = "https://github.com/cita-cloud/libproto" }

cloud-util = { git = "https://github.com/cita-cloud/cloud-util" }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto" }
status_code = { package = "cloud-code", git = "https://github.com/cita-cloud/status_code" }

[dependencies.cita-vm]
version = "0.2"
default-features = false
features = ["sha3hash"]

[dev-dependencies]
cpuprofiler = "0.0.4"
tempdir = "0.3.7"

[features]
default = ["sm2", "sm3hash", "hashlib-keccak"]
secp256k1 = ["cita-crypto/secp256k1", "libproto/secp256k1"]
sm2 = ["cita-crypto/sm2", "libproto/sm2"]
sha3hash = ["hashable/sha3hash", "libproto/sha3hash"]
sm3hash = ["hashable/sm3hash", "libproto/sm3hash"]
hashlib-keccak = ["tiny-keccak"]
hashlib-sha3 = ["sha3"]
